name: API and WEB UI Automation Testing   FinalProjectJayjay

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  API-and-WEB-AutomationTesting :
    runs-on: ubuntu-latest

    steps:
    #download repo
    - uses: actions/checkout@v4

    #setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    #install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

   #execute gradle command for running API test and WEB UI test
    - name: Setup Gradle 8.5
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5
    - name: Execute API test
      run: ./gradlew apiAutomationTesting

    - name: Execute WEB UI test
      run: ./gradlew webAutomationTesting

    #archieve test result
    - name: Archive Test Result
      uses: actions/upload-pages-artifact@v3.0.1
      if: always()
      with: 
        name: API and WEB UI report
        path: reports

    #deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports
